services:
  gateway:
    image: ghcr.io/alecicciarelli/demo_gateway_provenance:latest
    container_name: demo_gateway
    ports:
      - "9000:9000"
      - "11434:11434"
    env_file:
      - .env
    environment:
      OLLAMA_MODEL_NAME_NL: llama3-8b-dpo2-sft1-nl
      OLLAMA_MODEL_DIR_NL: /app/models/ft_nl
      OLLAMA_MODEL_NAME_SQL: llama3-8b-dpo1-sft2-sql
      OLLAMA_MODEL_DIR_SQL: /app/models/ft_sql
    volumes:
      - ./logs:/app/logs
      - ./faiss_index_tpch:/app/faiss_index_tpch
      - ollama_data:/root/.ollama

volumes:
  ollama_data: