services:
  ollama:
    image: ollama/ollama
    container_name: demo_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/models
    deploy:
      resources:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  ollama-init:
    image: ollama/ollama
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/models
    entrypoint: ["/bin/sh", "-c"]
    command: >
    
      "
      echo 'Waiting for Ollama...' &&
      until ollama list > /dev/null 2>&1; do
        sleep 2
      done &&
      echo 'Ollama ready' &&
      (ollama list | grep -q 'llama3:8b' || ollama pull llama3:8b) &&
      (ollama list | grep -q 'llama3-8b-dpo2-sft1-nl' || ollama create llama3-8b-dpo2-sft1-nl -f /models/ft_nl/Modelfile) &&
      (ollama list | grep -q 'llama3-8b-dpo1-sft2-sql' || ollama create llama3-8b-dpo1-sft2-sql -f /models/ft_sql/Modelfile)
      "

  gateway:
    image: ghcr.io/alecicciarelli/demo_gateway_provenance:latest
    container_name: demo_gateway
    depends_on:
      ollama:
        condition: service_started
      ollama-init:
        condition: service_completed_successfully
    ports:
      - "9005:9000"
    env_file:
      - .env
    environment:
      OLLAMA_HOST: http://ollama:11434
    volumes:
      - ./logs:/app/logs
      - ./faiss_index_tpch:/app/faiss_index_tpch
      - ./tpch_no_provsql:/app/tpch_no_provsql
    deploy:
      resources:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

volumes:
  ollama_data: